FROM node:18.15.0

EXPOSE 3000

WORKDIR /app

RUN npm install --global serve

COPY package*.json /app/

RUN npm ci

COPY . .

RUN npm run build

# Use npx to serve the built files
CMD ["npx", "serve","dist"]
